// for select inputs
export const genderOptions = [
	{ value: "male", valueToDisplay: "Male" },
	{ value: "female", valueToDisplay: "Female" },
	{ value: "other", valueToDisplay: "Other" },
];

export const preferedGenderOptions = [
	{ value: "male", valueToDisplay: "Male" },
	{ value: "female", valueToDisplay: "Female" },
	{ value: "both", valueToDisplay: "Both" },
];

export const qualificationOptions = [
	{ value: "no_education", valueToDisplay: "No Formal Education" },
	{ value: "primary_school", valueToDisplay: "Primary School" },
	{ value: "high_school", valueToDisplay: "High School Diploma" },
	{
		value: "vocational_training",
		valueToDisplay: "Vocational Training/Certificate",
	},
	{ value: "diploma", valueToDisplay: "Diploma" },
	{ value: "associate_degree", valueToDisplay: "Associate Degree" },
	{
		value: "bachelor",
		valueToDisplay: "Bachelor's Degree (B.A./B.Sc./B.E./B.Tech)",
	},
	{
		value: "master",
		valueToDisplay: "Master's Degree (M.A./M.Sc./M.E./M.Tech/MBA)",
	},
	{ value: "doctorate", valueToDisplay: "Doctorate (Ph.D./D.Phil.)" },
	{ value: "post_doctoral", valueToDisplay: "Post-Doctoral Studies" },
	{
		value: "professional_certification",
		valueToDisplay: "Professional Certification",
	},
	{ value: "other", valueToDisplay: "Other" },
];

export const educationType = [
	{ value: "part_time", valueToDisplay: "Part Time" },
	{ value: "full_time", valueToDisplay: "Full Time" },
	{ value: "distance", valueToDisplay: "Distance" },
];
export const preferredJobType = [
	{ value: "", valueToDisplay: "Choose a category" },
	{ value: "On-site", valueToDisplay: "On-site" },
	{ value: "W-F-H", valueToDisplay: "W-F-H" },
	{ value: "Hybrid", valueToDisplay: "Hybrid" },
	{ value: "part_time", valueToDisplay: "Part Time" },
	{ value: "full_time", valueToDisplay: "Full Time" },
	{ value: "contract", valueToDisplay: "Contract" },
	{ value: "internship", valueToDisplay: "Internship" },
	{ value: "remote", valueToDisplay: "Remote" },
	{ value: "temporary", valueToDisplay: "Temporary" },
	{ value: "volunteer", valueToDisplay: "Volunteer" },
	{ value: "freelance", valueToDisplay: "Freelance" },
	{ value: "any", valueToDisplay: "Any" },
];

export const jobTypes = [
	{ value: "web_developer", valueToDisplay: "Web Developer" },
	{ value: "graphics_designer", valueToDisplay: "Graphics Designer" },
	{ value: "ui_ux_designer", valueToDisplay: "UI/UX Designer" },
	{ value: "frontend_developer", valueToDisplay: "Frontend Developer" },
	{ value: "backend_developer", valueToDisplay: "Backend Developer" },
	{ value: "full_stack_developer", valueToDisplay: "Full Stack Developer" },
	{ value: "mobile_app_developer", valueToDisplay: "Mobile App Developer" },
	{ value: "data_analyst", valueToDisplay: "Data Analyst" },
	{ value: "seo_specialist", valueToDisplay: "SEO Specialist" },
	{ value: "digital_marketer", valueToDisplay: "Digital Marketer" },
	{ value: "project_manager", valueToDisplay: "Project Manager" },
	{ value: "content_writer", valueToDisplay: "Content Writer" },
	{ value: "qa_engineer", valueToDisplay: "QA Engineer" },
];

export const companySizeOptions = [
	{ value: "1-10", valueToDisplay: "1-10" },
	{ value: "11-50", valueToDisplay: "11-50" },
	{ value: "51-200", valueToDisplay: "51-200" },
	{ value: "201-500", valueToDisplay: "201-500" },
	{ value: "501-1000", valueToDisplay: "501-1000" },
	{ value: "1001+", valueToDisplay: "1001+" },
];

export const industyTypeOptions = [
	{ value: "IT", valueToDisplay: "IT" },
	{ value: "Finance", valueToDisplay: "Finance" },
	{ value: "Healthcare", valueToDisplay: "Healthcare" },
	{ value: "Energy", valueToDisplay: "Energy" },
	{ value: "Manufacturing", valueToDisplay: "Manufacturing" },
	{ value: "Retail", valueToDisplay: "Retail" },
	{ value: "Education", valueToDisplay: "Education" },
	{ value: "Government", valueToDisplay: "Government" },
	{ value: "Other", valueToDisplay: "Other" },
];

// for multiple select inputs
export const skillOptions = [
	{ value: "javascript", label: "JavaScript" },
	{ value: "python", label: "Python" },
	{ value: "java", label: "Java" },
	{ value: "csharp", label: "C#" },
	{ value: "ruby", label: "Ruby" },
	{ value: "go", label: "Go" },
	{ value: "html", label: "HTML" },
	{ value: "css", label: "CSS" },
	{ value: "react", label: "React.js" },
	{ value: "angular", label: "Angular" },
	{ value: "vue", label: "Vue.js" },
	{ value: "nodejs", label: "Node.js" },
	{ value: "express", label: "Express.js" },
	{ value: "mongodb", label: "MongoDB" },
	{ value: "mysql", label: "MySQL" },
	{ value: "postgresql", label: "PostgreSQL" },
	{ value: "sql", label: "SQL" },
	{ value: "docker", label: "Docker" },
	{ value: "kubernetes", label: "Kubernetes" },
	{ value: "aws", label: "AWS" },
	{ value: "azure", label: "Azure" },
	{ value: "googlecloud", label: "Google Cloud" },
	{ value: "git", label: "Git" },
	{ value: "github", label: "GitHub" },
	{ value: "gitlab", label: "GitLab" },
	{ value: "ci_cd", label: "CI/CD" },
	{ value: "jest", label: "Jest" },
	{ value: "mocha", label: "Mocha" },
	{ value: "typescript", label: "TypeScript" },
	{ value: "sass", label: "Sass" },
	{ value: "graphql", label: "GraphQL" },
	{ value: "redux", label: "Redux" },
	{ value: "tailwindcss", label: "Tailwind CSS" },
	{ value: "bootstrap", label: "Bootstrap" },
	{ value: "webpack", label: "Webpack" },
	{ value: "firebase", label: "Firebase" },
	{ value: "jest", label: "Jest" },
	{ value: "selenium", label: "Selenium" },
	{ value: "scrum", label: "Scrum" },
	{ value: "agile", label: "Agile" },
	{ value: "vscode", label: "Visual Studio Code" },
	{ value: "docker", label: "Docker" },
	{ value: "linux", label: "Linux" },
	{ value: "windows", label: "Windows" },
	{ value: "machinelearning", label: "Machine Learning" },
	{ value: "deep_learning", label: "Deep Learning" },
	{ value: "tensorflow", label: "TensorFlow" },
	{ value: "pytorch", label: "PyTorch" },
	{ value: "opencv", label: "OpenCV" },
	{ value: "r", label: "R" },
	{ value: "tableau", label: "Tableau" },
	{ value: "powerbi", label: "Power BI" },
	{ value: "spark", label: "Apache Spark" },
	{ value: "hadoop", label: "Hadoop" },
	{ value: "sqlalchemy", label: "SQLAlchemy" },
	{ value: "elasticsearch", label: "Elasticsearch" },
	{ value: "redis", label: "Redis" },
	{ value: "kafka", label: "Apache Kafka" },
	{ value: "rabbitmq", label: "RabbitMQ" },
	{ value: "azuredevops", label: "Azure DevOps" },
	{ value: "jenkins", label: "Jenkins" },
	{ value: "cloudformation", label: "CloudFormation" },
	{ value: "ansible", label: "Ansible" },
	{ value: "terraform", label: "Terraform" },
	{ value: "nginx", label: "Nginx" },
	{ value: "apache", label: "Apache" },
	{ value: "rails", label: "Ruby on Rails" },
	{ value: "flutter", label: "Flutter" },
	{ value: "swift", label: "Swift" },
	{ value: "kotlin", label: "Kotlin" },
	{ value: "xcode", label: "Xcode" },
	{ value: "android", label: "Android Development" },
	{ value: "ios", label: "iOS Development" },
	{ value: "reactnative", label: "React Native" },
	{ value: "ember", label: "Ember.js" },
	{ value: "laravel", label: "Laravel" },
	{ value: "symfony", label: "Symfony" },
];

export const locationOptions = [
	{
		value: "kochi",
		label: "Kochi",
	},
	{ value: "kollam", label: "Kollam" },
	{ value: "kozhikode", label: "Kozhikode" },
	{ value: "alappuzha", label: "Alappuzha" },
	{ value: "ernakulam", label: "Ernakulam" },
	{ value: "idukki", label: "Idukki" },
	{ value: "kannur", label: "Kannur" },
	{ value: "kasaragod", label: "Kasaragod" },
	{ value: "kottayam", label: "Kottayam" },
	{ value: "malappuram", label: "Malappuram" },
	{ value: "palakkad", label: "Palakkad" },
	{ value: "pathanamthitta", label: "Pathanamthitta" },
	{ value: "thiruvananthapuram", label: "Thiruvananthapuram" },
	{ value: "thrissur", label: "Thrissur" },
	{ value: "wayanad", label: "Wayanad" },
];

export const professions = [
	{ value: "software_development", label: "Software Development", category: "Information Technology (IT)" },
	{ value: "data_science", label: "Data Science", category: "Information Technology (IT)" },
	{ value: "cybersecurity", label: "Cybersecurity", category: "Information Technology (IT)" },
	{ value: "cloud_computing", label: "Cloud Computing", category: "Information Technology (IT)" },
	{ value: "devops", label: "DevOps", category: "Information Technology (IT)" },
	{ value: "game_development", label: "Game Development", category: "Information Technology (IT)" },
	{ value: "nursing", label: "Nursing", category: "Healthcare" },
	{ value: "medicine", label: "Medicine", category: "Healthcare" },
	{ value: "pharmacy", label: "Pharmacy", category: "Healthcare" },
	{ value: "physical_therapy", label: "Physical Therapy", category: "Healthcare" },
	{ value: "radiology", label: "Radiology", category: "Healthcare" },
	{ value: "medical_coding", label: "Medical Coding", category: "Healthcare" },
	{ value: "accounting", label: "Accounting", category: "Finance & Accounting" },
	{ value: "financial_analysis", label: "Financial Analysis", category: "Finance & Accounting" },
	{ value: "auditing", label: "Auditing", category: "Finance & Accounting" },
	{ value: "tax_consultancy", label: "Tax Consultancy", category: "Finance & Accounting" },
	{ value: "investment_banking", label: "Investment Banking", category: "Finance & Accounting" },
	{ value: "digital_marketing", label: "Digital Marketing", category: "Marketing & Sales" },
	{ value: "sales", label: "Sales", category: "Marketing & Sales" },
	{ value: "branding", label: "Branding", category: "Marketing & Sales" },
	{ value: "content_strategy", label: "Content Strategy", category: "Marketing & Sales" },
	{ value: "public_relations", label: "Public Relations", category: "Marketing & Sales" },
	{ value: "mechanical_engineering", label: "Mechanical Engineering", category: "Engineering" },
	{ value: "civil_engineering", label: "Civil Engineering", category: "Engineering" },
	{ value: "electrical_engineering", label: "Electrical Engineering", category: "Engineering" },
	{ value: "robotics_engineering", label: "Robotics Engineering", category: "Engineering" },
	{ value: "structural_engineering", label: "Structural Engineering", category: "Engineering" },
	{ value: "teaching", label: "Teaching", category: "Education" },
	{ value: "academic_counseling", label: "Academic Counseling", category: "Education" },
	{ value: "curriculum_development", label: "Curriculum Development", category: "Education" },
	{ value: "educational_consulting", label: "Educational Consulting", category: "Education" },
	{ value: "graphic_design", label: "Graphic Design", category: "Creative Arts & Design" },
	{ value: "photography", label: "Photography", category: "Creative Arts & Design" },
	{ value: "interior_design", label: "Interior Design", category: "Creative Arts & Design" },
	{ value: "animation", label: "Animation", category: "Creative Arts & Design" },
	{ value: "video_editing", label: "Video Editing", category: "Creative Arts & Design" },
	{ value: "hotel_management", label: "Hotel Management", category: "Hospitality & Tourism" },
	{ value: "event_planning", label: "Event Planning", category: "Hospitality & Tourism" },
	{ value: "culinary_arts", label: "Culinary Arts", category: "Hospitality & Tourism" },
	{ value: "tourism_management", label: "Tourism Management", category: "Hospitality & Tourism" },
	{ value: "law", label: "Law", category: "Legal & Compliance" },
	{ value: "paralegal_services", label: "Paralegal Services", category: "Legal & Compliance" },
	{ value: "corporate_legal_services", label: "Corporate Legal Services", category: "Legal & Compliance" },
	{ value: "compliance_management", label: "Compliance Management", category: "Legal & Compliance" },
	{ value: "logistics_management", label: "Logistics Management", category: "Logistics & Supply Chain" },
	{ value: "supply_chain_coordination", label: "Supply Chain Coordination", category: "Logistics & Supply Chain" },
	{ value: "inventory_management", label: "Inventory Management", category: "Logistics & Supply Chain" },
	{ value: "talent_management", label: "Talent Management", category: "Human Resources (HR)" },
	{ value: "recruitment", label: "Recruitment", category: "Human Resources (HR)" },
	{ value: "payroll_administration", label: "Payroll Administration", category: "Human Resources (HR)" }
];

export const jobTitles = [
	{ value: "software_engineer", label: "Software Engineer", category: "information_technology_(it)" },
	{ value: "web_developer", label: "Web Developer", category: "information_technology_(it)" },
	{ value: "data_analyst", label: "Data Analyst", category: "information_technology_(it)" },
	{ value: "cloud_engineer", label: "Cloud Engineer", category: "information_technology_(it)" },
	{ value: "network_administrator", label: "Network Administrator", category: "information_technology_(it)" },
	{ value: "it_support_specialist", label: "IT Support Specialist", category: "information_technology_(it)" },
	{ value: "mobile_app_developer", label: "Mobile App Developer", category: "information_technology_(it)" },
	{ value: "cybersecurity_specialist", label: "Cybersecurity Specialist", category: "information_technology_(it)" },
	{ value: "ai_ml_engineer", label: "AI/ML Engineer", category: "information_technology_(it)" },
	{ value: "database_administrator", label: "Database Administrator", category: "information_technology_(it)" },
	{ value: "registered_nurse", label: "Registered Nurse", category: "healthcare" },
	{ value: "general_practitioner", label: "General Practitioner", category: "healthcare" },
	{ value: "pharmacist", label: "Pharmacist", category: "healthcare" },
	{ value: "medical_assistant", label: "Medical Assistant", category: "healthcare" },
	{ value: "physical_therapist", label: "Physical Therapist", category: "healthcare" },
	{ value: "surgeon", label: "Surgeon", category: "healthcare" },
	{ value: "radiologic_technologist", label: "Radiologic Technologist", category: "healthcare" },
	{ value: "medical_transcriptionist", label: "Medical Transcriptionist", category: "healthcare" },
	{ value: "dental_hygienist", label: "Dental Hygienist", category: "healthcare" },
	{ value: "accountant", label: "Accountant", category: "finance_&_accounting" },
	{ value: "budget_analyst", label: "Budget Analyst", category: "finance_&_accounting" },
	{ value: "tax_advisor", label: "Tax Advisor", category: "finance_&_accounting" },
	{ value: "financial_planner", label: "Financial Planner", category: "finance_&_accounting" },
	{ value: "investment_analyst", label: "Investment Analyst", category: "finance_&_accounting" },
	{ value: "credit_analyst", label: "Credit Analyst", category: "finance_&_accounting" },
	{ value: "payroll_coordinator", label: "Payroll Coordinator", category: "finance_&_accounting" },
	{ value: "internal_auditor", label: "Internal Auditor", category: "finance_&_accounting" },
	{ value: "marketing_manager", label: "Marketing Manager", category: "marketing_&_sales" },
	{ value: "sales_representative", label: "Sales Representative", category: "marketing_&_sales" },
	{ value: "brand_strategist", label: "Brand Strategist", category: "marketing_&_sales" },
	{ value: "social_media_specialist", label: "Social Media Specialist", category: "marketing_&_sales" },
	{ value: "seo_specialist", label: "SEO Specialist", category: "marketing_&_sales" },
	{ value: "content_marketing_manager", label: "Content Marketing Manager", category: "marketing_&_sales" },
	{ value: "product_manager", label: "Product Manager", category: "marketing_&_sales" },
	{ value: "advertising_coordinator", label: "Advertising Coordinator", category: "marketing_&_sales" },
	{ value: "mechanical_engineer", label: "Mechanical Engineer", category: "engineering" },
	{ value: "electrical_engineer", label: "Electrical Engineer", category: "engineering" },
	{ value: "civil_engineer", label: "Civil Engineer", category: "engineering" },
	{ value: "petroleum_engineer", label: "Petroleum Engineer", category: "engineering" },
	{ value: "biomedical_engineer", label: "Biomedical Engineer", category: "engineering" },
	{ value: "chemical_engineer", label: "Chemical Engineer", category: "engineering" },
	{ value: "environmental_engineer", label: "Environmental Engineer", category: "engineering" },
	{ value: "aerospace_engineer", label: "Aerospace Engineer", category: "engineering" },
	{ value: "teacher", label: "Teacher", category: "education" },
	{ value: "principal", label: "Principal", category: "education" },
	{ value: "school_counselor", label: "School Counselor", category: "education" },
	{ value: "professor", label: "Professor", category: "education" },
	{ value: "instructional_designer", label: "Instructional Designer", category: "education" },
	{ value: "librarian", label: "Librarian", category: "education" },
	{ value: "special_education_teacher", label: "Special Education Teacher", category: "education" },
	{ value: "academic_coordinator", label: "Academic Coordinator", category: "education" },
	{ value: "graphic_designer", label: "Graphic Designer", category: "creative_arts_&_design" },
	{ value: "art_director", label: "Art Director", category: "creative_arts_&_design" },
	{ value: "ux_designer", label: "UX Designer", category: "creative_arts_&_design" },
	{ value: "motion_graphics_artist", label: "Motion Graphics Artist", category: "creative_arts_&_design" },
	{ value: "animator", label: "Animator", category: "creative_arts_&_design" },
	{ value: "copywriter", label: "Copywriter", category: "creative_arts_&_design" },
	{ value: "interior_decorator", label: "Interior Decorator", category: "creative_arts_&_design" },
	{ value: "fashion_designer", label: "Fashion Designer", category: "creative_arts_&_design" },
	{ value: "hotel_receptionist", label: "Hotel Receptionist", category: "hospitality_&_tourism" },
	{ value: "event_planner", label: "Event Planner", category: "hospitality_&_tourism" },
	{ value: "travel_agent", label: "Travel Agent", category: "hospitality_&_tourism" },
	{ value: "tour_operator", label: "Tour Operator", category: "hospitality_&_tourism" },
	{ value: "concierge", label: "Concierge", category: "hospitality_&_tourism" },
	{ value: "food_and_beverage_manager", label: "Food and Beverage Manager", category: "hospitality_&_tourism" },
	{ value: "front_desk_manager", label: "Front Desk Manager", category: "hospitality_&_tourism" },
	{ value: "housekeeping_supervisor", label: "Housekeeping Supervisor", category: "hospitality_&_tourism" },
	{ value: "attorney", label: "Attorney", category: "legal_&_compliance" },
	{ value: "legal_secretary", label: "Legal Secretary", category: "legal_&_compliance" },
	{ value: "contract_manager", label: "Contract Manager", category: "legal_&_compliance" },
	{ value: "compliance_analyst", label: "Compliance Analyst", category: "legal_&_compliance" },
	{ value: "legal_consultant", label: "Legal Consultant", category: "legal_&_compliance" },
	{ value: "paralegal", label: "Paralegal", category: "legal_&_compliance" },
	{ value: "corporate_counsel", label: "Corporate Counsel", category: "legal_&_compliance" },
	{ value: "logistics_manager", label: "Logistics Manager", category: "logistics_&_supply_chain" },
	{ value: "warehouse_supervisor", label: "Warehouse Supervisor", category: "logistics_&_supply_chain" },
	{ value: "transportation_planner", label: "Transportation Planner", category: "logistics_&_supply_chain" },
	{ value: "supply_chain_analyst", label: "Supply Chain Analyst", category: "logistics_&_supply_chain" },
	{ value: "procurement_manager", label: "Procurement Manager", category: "logistics_&_supply_chain" },
	{ value: "inventory_specialist", label: "Inventory Specialist", category: "logistics_&_supply_chain" },
	{ value: "freight_coordinator", label: "Freight Coordinator", category: "logistics_&_supply_chain" },
	{ value: "hr_generalist", label: "HR Generalist", category: "human_resources_(hr)" },
	{ value: "talent_acquisition_specialist", label: "Talent Acquisition Specialist", category: "human_resources_(hr)" },
	{ value: "compensation_and_benefits_manager", label: "Compensation and Benefits Manager", category: "human_resources_(hr)" },
	{ value: "training_and_development_coordinator", label: "Training and Development Coordinator", category: "human_resources_(hr)" },
	{ value: "employee_engagement_specialist", label: "Employee Engagement Specialist", category: "human_resources_(hr)" },
	{ value: "hr_business_partner", label: "HR Business Partner", category: "human_resources_(hr)" }
];

// job portal data
export const categoryData = [
	{ value: "On-site", valueToDisplay: "On-site" },
	{ value: "Remote", valueToDisplay: "Remote" },
	{ value: "W-F-H", valueToDisplay: "W-F-H" },
	{ value: "Hybrid", valueToDisplay: "Hybrid" },
];
// job Status
export const JobStatusData = [
	{ value: "Active", valueToDisplay: "Active" },
	{ value: "Closed", valueToDisplay: "Closed" },
	{ value: "Paused", valueToDisplay: "Paused" },
	{ value: "Inactive", valueToDisplay: "Inactive" },
];

export const postedDateData = [
	"All",
	"Last Hour",
	"Last 24 Hours",
	"Last 7 Days",
	"Last 14 Days",
	"Last 30 Days",
];

export const experienceData = [
	{ value: "fresher", valueToDisplay: "Fresher" },
	{ value: "0-1", valueToDisplay: "0-1" },
	{ value: "1-2", valueToDisplay: "1-2" },
	{ value: "2-3", valueToDisplay: "2-3" },
	{ value: "4-6", valueToDisplay: "4-6" },
	{ value: "6-8", valueToDisplay: "6-8" },
	{ value: "8-10", valueToDisplay: "8-10" },
	{ value: "10-12", valueToDisplay: "10-12" },
	{ value: "12-14", valueToDisplay: "12-14" },
	{ value: "14-16", valueToDisplay: "14-16" },
	{ value: "16-18", valueToDisplay: "16-18" },
	{ value: "18-20", valueToDisplay: "18-20" },
	{ value: ">20", valueToDisplay: ">20" },
];

export const filterSkillOptions = [
	// Information Technology (IT)
	{ value: "python", valueToDisplay: "Python", category: "Information Technology (IT)" },
	{ value: "java", valueToDisplay: "Java", category: "Information Technology (IT)" },
	{ value: "cpp", valueToDisplay: "C++", category: "Information Technology (IT)" },
	{ value: "javascript", valueToDisplay: "JavaScript", category: "Information Technology (IT)" },
	{ value: "html", valueToDisplay: "HTML", category: "Information Technology (IT)" },
	{ value: "css", valueToDisplay: "CSS", category: "Information Technology (IT)" },
	{ value: "react", valueToDisplay: "React", category: "Information Technology (IT)" },
	{ value: "angular", valueToDisplay: "Angular", category: "Information Technology (IT)" },
	{ value: "sql", valueToDisplay: "SQL", category: "Information Technology (IT)" },
	{ value: "powerbi", valueToDisplay: "Power BI", category: "Information Technology (IT)" },
	{ value: "tableau", valueToDisplay: "Tableau", category: "Information Technology (IT)" },
	{ value: "aws", valueToDisplay: "AWS", category: "Information Technology (IT)" },
	{ value: "azure", valueToDisplay: "Azure", category: "Information Technology (IT)" },
	{ value: "googlecloud", valueToDisplay: "Google Cloud", category: "Information Technology (IT)" },
	{ value: "machine_learning", valueToDisplay: "Machine Learning", category: "Information Technology (IT)" },
	{ value: "artificial_intelligence", valueToDisplay: "Artificial Intelligence", category: "Information Technology (IT)" },
	{ value: "cybersecurity", valueToDisplay: "Cybersecurity", category: "Information Technology (IT)" },
	{ value: "penetration_testing", valueToDisplay: "Penetration Testing", category: "Information Technology (IT)" },
	{ value: "network_security", valueToDisplay: "Network Security", category: "Information Technology (IT)" },
	{ value: "git", valueToDisplay: "Git", category: "Information Technology (IT)" },
	{ value: "github", valueToDisplay: "GitHub", category: "Information Technology (IT)" },
	{ value: "docker", valueToDisplay: "Docker", category: "Information Technology (IT)" },
	{ value: "kubernetes", valueToDisplay: "Kubernetes", category: "Information Technology (IT)" },
	{ value: "jenkins", valueToDisplay: "Jenkins", category: "Information Technology (IT)" },
	{ value: "mongodb", valueToDisplay: "MongoDB", category: "Information Technology (IT)" },
	{ value: "mysql", valueToDisplay: "MySQL", category: "Information Technology (IT)" },
	{ value: "postgresql", valueToDisplay: "PostgreSQL", category: "Information Technology (IT)" },
	{ value: "android", valueToDisplay: "Android Development", category: "Information Technology (IT)" },
	{ value: "ios", valueToDisplay: "iOS Development", category: "Information Technology (IT)" },
	{ value: "flutter", valueToDisplay: "Flutter", category: "Information Technology (IT)" },

	// Healthcare
	{ value: "patient_care", valueToDisplay: "Patient Care", category: "Healthcare" },
	{ value: "medical_terminology", valueToDisplay: "Medical Terminology", category: "Healthcare" },
	{ value: "diagnostic_testing", valueToDisplay: "Diagnostic Testing", category: "Healthcare" },
	{ value: "first_aid", valueToDisplay: "First Aid & CPR", category: "Healthcare" },
	{ value: "clinical_documentation", valueToDisplay: "Clinical Documentation", category: "Healthcare" },
	{ value: "ehr_management", valueToDisplay: "Electronic Health Records (EHR) Management", category: "Healthcare" },
	{ value: "pharmacy_management", valueToDisplay: "Pharmacy Management", category: "Healthcare" },
	{ value: "surgical_assistance", valueToDisplay: "Surgical Assistance", category: "Healthcare" },
	{ value: "physiotherapy_techniques", valueToDisplay: "Physiotherapy Techniques", category: "Healthcare" },
	{ value: "medical_billing_coding", valueToDisplay: "Medical Billing & Coding", category: "Healthcare" },

	// Finance & Accounting
	{ value: "financial_analysis", valueToDisplay: "Financial Analysis", category: "Finance & Accounting" },
	{ value: "budgeting", valueToDisplay: "Budgeting & Forecasting", category: "Finance & Accounting" },
	{ value: "tax_planning", valueToDisplay: "Tax Planning & Compliance", category: "Finance & Accounting" },
	{ value: "risk_management", valueToDisplay: "Risk Management", category: "Finance & Accounting" },
	{ value: "accounting_software", valueToDisplay: "Accounting Software (Tally, QuickBooks, SAP)", category: "Finance & Accounting" },
	{ value: "financial_modeling", valueToDisplay: "Financial Modeling", category: "Finance & Accounting" },
	{ value: "investment_analysis", valueToDisplay: "Investment Analysis", category: "Finance & Accounting" },
	{ value: "cost_accounting", valueToDisplay: "Cost Accounting", category: "Finance & Accounting" },
	{ value: "payroll_processing", valueToDisplay: "Payroll Processing", category: "Finance & Accounting" },
	{ value: "auditing_techniques", valueToDisplay: "Auditing Techniques", category: "Finance & Accounting" },

	// Marketing & Sales
	{ value: "seo", valueToDisplay: "Search Engine Optimization (SEO)", category: "Marketing & Sales" },
	{ value: "content_creation", valueToDisplay: "Content Creation & Strategy", category: "Marketing & Sales" },
	{ value: "social_media_management", valueToDisplay: "Social Media Management", category: "Marketing & Sales" },
	{ value: "email_marketing", valueToDisplay: "Email Marketing", category: "Marketing & Sales" },
	{ value: "google_ads", valueToDisplay: "Google Ads & PPC Campaigns", category: "Marketing & Sales" },
	{ value: "crm_software", valueToDisplay: "CRM Software", category: "Marketing & Sales" },
	{ value: "market_research", valueToDisplay: "Market Research & Analysis", category: "Marketing & Sales" },
	{ value: "brand_positioning", valueToDisplay: "Brand Positioning", category: "Marketing & Sales" },
	{ value: "sales_negotiation", valueToDisplay: "Sales Negotiation Techniques", category: "Marketing & Sales" },
	{ value: "lead_generation", valueToDisplay: "Lead Generation", category: "Marketing & Sales" },

	// Engineering
	{ value: "cad_software", valueToDisplay: "CAD Software (AutoCAD, SolidWorks, Revit)", category: "Engineering" },
	{ value: "project_management", valueToDisplay: "Project Management", category: "Engineering" },
	{ value: "structural_analysis", valueToDisplay: "Structural Analysis", category: "Engineering" },
	{ value: "circuit_design", valueToDisplay: "Circuit Design", category: "Engineering" },
	{ value: "robotics_programming", valueToDisplay: "Robotics Programming", category: "Engineering" },
	{ value: "thermodynamics", valueToDisplay: "Thermodynamics", category: "Engineering" },
	{ value: "industrial_automation", valueToDisplay: "Industrial Automation", category: "Engineering" },
	{ value: "materials_testing", valueToDisplay: "Materials Testing", category: "Engineering" },
	{ value: "3d_printing", valueToDisplay: "3D Printing & Prototyping", category: "Engineering" },
	{ value: "renewable_energy", valueToDisplay: "Renewable Energy Systems", category: "Engineering" },

	// Education
	{ value: "curriculum_design", valueToDisplay: "Curriculum Design", category: "Education" },
	{ value: "lesson_planning", valueToDisplay: "Lesson Planning", category: "Education" },
	{ value: "classroom_management", valueToDisplay: "Classroom Management", category: "Education" },
	{ value: "e_learning_tools", valueToDisplay: "E-Learning Tools (Moodle, Blackboard, Google Classroom)", category: "Education" },
	{ value: "public_speaking", valueToDisplay: "Public Speaking", category: "Education" },
	{ value: "student_assessment", valueToDisplay: "Student Assessment & Evaluation", category: "Education" },
	{ value: "special_education", valueToDisplay: "Special Education Techniques", category: "Education" },
	{ value: "educational_technology", valueToDisplay: "Educational Technology Integration", category: "Education" },
	{ value: "academic_research", valueToDisplay: "Research & Academic Writing", category: "Education" },

	// Creative Arts & Design
	{ value: "graphic_design", valueToDisplay: "Graphic Design (Adobe Photoshop, Illustrator, CorelDRAW)", category: "Creative Arts & Design" },
	{ value: "video_editing", valueToDisplay: "Video Editing (Adobe Premiere Pro, Final Cut Pro)", category: "Creative Arts & Design" },
	{ value: "motion_graphics", valueToDisplay: "Motion Graphics & Animation (After Effects, Blender)", category: "Creative Arts & Design" },
	{ value: "ux_ui_design", valueToDisplay: "UX/UI Design Principles", category: "Creative Arts & Design" },
	{ value: "photography", valueToDisplay: "Photography & Photo Editing", category: "Creative Arts & Design" },
	{ value: "creative_writing", valueToDisplay: "Creative Writing", category: "Creative Arts & Design" },
	{ value: "3d_modeling", valueToDisplay: "3D Modeling & Rendering", category: "Creative Arts & Design" },
	{ value: "color_theory", valueToDisplay: "Color Theory & Typography", category: "Creative Arts & Design" },
	{ value: "visual_storytelling", valueToDisplay: "Visual Storytelling", category: "Creative Arts & Design" },
	{ value: "fashion_illustration", valueToDisplay: "Fashion Illustration", category: "Creative Arts & Design" },

	// Hospitality & Tourism
	{ value: "customer_service", valueToDisplay: "Customer Service", category: "Hospitality & Tourism" },
	{ value: "event_planning", valueToDisplay: "Event Planning & Coordination", category: "Hospitality & Tourism" },
	{ value: "food_preparation", valueToDisplay: "Food Preparation & Presentation", category: "Hospitality & Tourism" },
	{ value: "hospitality_management", valueToDisplay: "Hospitality Management", category: "Hospitality & Tourism" },
	{ value: "travel_itinerary", valueToDisplay: "Travel Itinerary Planning", category: "Hospitality & Tourism" },
	{ value: "reservation_systems", valueToDisplay: "Reservation Systems (Opera, Amadeus)", category: "Hospitality & Tourism" },
	{ value: "time_management", valueToDisplay: "Multi-tasking & Time Management", category: "Hospitality & Tourism" },
	{ value: "conflict_resolution", valueToDisplay: "Conflict Resolution", category: "Hospitality & Tourism" },
	{ value: "cultural_sensitivity", valueToDisplay: "Cultural Sensitivity", category: "Hospitality & Tourism" },

	// Logistics & Supply Chain
	{ value: "inventory_management", valueToDisplay: "Inventory Management", category: "Logistics & Supply Chain" },
	{ value: "supply_chain_optimization", valueToDisplay: "Supply Chain Optimization", category: "Logistics & Supply Chain" },
	{ value: "procurement_management", valueToDisplay: "Procurement & Vendor Management", category: "Logistics & Supply Chain" },
	{ value: "transportation_coordination", valueToDisplay: "Transportation Coordination", category: "Logistics & Supply Chain" },
	{ value: "warehouse_management", valueToDisplay: "Warehouse Management", category: "Logistics & Supply Chain" },
	{ value: "erp_systems", valueToDisplay: "ERP Systems (SAP, Oracle)", category: "Logistics & Supply Chain" },
	{ value: "demand_forecasting", valueToDisplay: "Demand Forecasting", category: "Logistics & Supply Chain" },
	{ value: "logistics_planning", valueToDisplay: "Logistics Planning", category: "Logistics & Supply Chain" },
	{ value: "cost_control", valueToDisplay: "Cost Control Techniques", category: "Logistics & Supply Chain" },

	// Human Resources (HR)
	{ value: "talent_acquisition", valueToDisplay: "Talent Acquisition", category: "Human Resources (HR)" },
	{ value: "employee_engagement", valueToDisplay: "Employee Engagement", category: "Human Resources (HR)" },
	{ value: "training_development", valueToDisplay: "Training & Development", category: "Human Resources (HR)" },
	{ value: "performance_management", valueToDisplay: "Performance Management", category: "Human Resources (HR)" },
	{ value: "hrms_software", valueToDisplay: "HRMS Software (Workday, BambooHR)", category: "Human Resources (HR)" },
	{ value: "compensation_benefits", valueToDisplay: "Compensation & Benefits Planning", category: "Human Resources (HR)" },
	{ value: "conflict_resolution", valueToDisplay: "Conflict Resolution", category: "Human Resources (HR)" },
	{ value: "onboarding_processes", valueToDisplay: "Onboarding Processes", category: "Human Resources (HR)" },
	{ value: "leadership_development", valueToDisplay: "Leadership Development", category: "Human Resources (HR)" },

	// Legal & Compliance
	{ value: "legal_drafting", valueToDisplay: "Legal Drafting", category: "Legal & Compliance" },
	{ value: "contract_negotiation", valueToDisplay: "Contract Negotiation", category: "Legal & Compliance" },
	{ value: "corporate_law", valueToDisplay: "Corporate Law Knowledge", category: "Legal & Compliance" },
	{ value: "regulatory_compliance", valueToDisplay: "Regulatory Compliance", category: "Legal & Compliance" },
	{ value: "intellectual_property", valueToDisplay: "Intellectual Property Law", category: "Legal & Compliance" },
	{ value: "litigation_management", valueToDisplay: "Litigation Management", category: "Legal & Compliance" },
	{ value: "mediation_arbitration", valueToDisplay: "Mediation & Arbitration Skills", category: "Legal & Compliance" },
	{ value: "research_legal_writing", valueToDisplay: "Research & Legal Writing", category: "Legal & Compliance" },
	{ value: "risk_assessment", valueToDisplay: "Risk Assessment", category: "Legal & Compliance" },
];

export const manageJobsMonthOptions = [
	{ value: "Last 6 Months", valueToDisplay: "Last 6 Months" },
	{ value: "Last 12 Months", valueToDisplay: "Last 12 Months" },
	{ value: "Last 16 Months", valueToDisplay: "Last 16 Months" },
	{ value: "Last 24 Months", valueToDisplay: "Last 24 Months" },
	{ value: "Last 5 Year", valueToDisplay: "Last 5 Year" },
];

export const salaryRanges = [
	{ value: "0-20000", valueToDisplay: "0-20,000" },
	{ value: "20001-40000", valueToDisplay: "20,001-40,000" },
	{ value: "40001-60000", valueToDisplay: "40,001-60,000" },
	{ value: "60001-80000", valueToDisplay: "60,001-80,000" },
	{ value: "80001-100000", valueToDisplay: "80,001-100,000" },
	{ value: "100001-120000", valueToDisplay: "100,001-120,000" },
	{ value: "120001-140000", valueToDisplay: "120,001-140,000" },
	{ value: "140001-160000", valueToDisplay: "140,001-160,000" },
	{ value: "160001-180000", valueToDisplay: "160,001-180,000" },
	{ value: "180001-200000", valueToDisplay: "180,001-200,000" },
	{ value: "200001+", valueToDisplay: "200,001+" },
];

export const joiningDayRange = [
	{ value: "immediate", valueToDisplay: "Immediate" },
	{ value: "within_1_week", valueToDisplay: "Within 1 Week" },
	{ value: "within_2_weeks", valueToDisplay: "Within 2 Weeks" },
	{ value: "within_1_month", valueToDisplay: "Within 1 Month" },
	{ value: "within_2_months", valueToDisplay: "Within 2 Months" },
	{ value: "within_3_months", valueToDisplay: "Within 3 Months" },
];


