// for select inputs
export const genderOptions = [
	{ value: "male", valueToDisplay: "Male" },
	{ value: "female", valueToDisplay: "Female" },
	{ value: "other", valueToDisplay: "Other" },
];

export const qualificationOptions = [
	{ value: "no_education", valueToDisplay: "No Formal Education" },
	{ value: "primary_school", valueToDisplay: "Primary School" },
	{ value: "high_school", valueToDisplay: "High School Diploma" },
	{
		value: "vocational_training",
		valueToDisplay: "Vocational Training/Certificate",
	},
	{ value: "diploma", valueToDisplay: "Diploma" },
	{ value: "associate_degree", valueToDisplay: "Associate Degree" },
	{
		value: "bachelor",
		valueToDisplay: "Bachelor's Degree (B.A./B.Sc./B.E./B.Tech)",
	},
	{
		value: "master",
		valueToDisplay: "Master's Degree (M.A./M.Sc./M.E./M.Tech/MBA)",
	},
	{ value: "doctorate", valueToDisplay: "Doctorate (Ph.D./D.Phil.)" },
	{ value: "post_doctoral", valueToDisplay: "Post-Doctoral Studies" },
	{
		value: "professional_certification",
		valueToDisplay: "Professional Certification",
	},
	{ value: "other", valueToDisplay: "Other" },
];

export const educationType = [
	{ value: "part_time", valueToDisplay: "Part Time" },
	{ value: "full_time", valueToDisplay: "Full Time" },
	{ value: "distance", valueToDisplay: "Distance" },
];
export const preferredJobType = [
	{ value: "", valueToDisplay: "Choose a category" },
	{ value: "On-site", valueToDisplay: "On-site" },
	{ value: "W-F-H", valueToDisplay: "W-F-H" },
	{ value: "Hybrid", valueToDisplay: "Hybrid" },
	{ value: "part_time", valueToDisplay: "Part Time" },
	{ value: "full_time", valueToDisplay: "Full Time" },
	{ value: "contract", valueToDisplay: "Contract" },
	{ value: "internship", valueToDisplay: "Internship" },
	{ value: "remote", valueToDisplay: "Remote" },
	{ value: "temporary", valueToDisplay: "Temporary" },
	{ value: "volunteer", valueToDisplay: "Volunteer" },
	{ value: "freelance", valueToDisplay: "Freelance" },
	{ value: "any", valueToDisplay: "Any" },
];

export const jobTypes = [
	{ value: "web_developer", valueToDisplay: "Web Developer" },
	{ value: "graphics_designer", valueToDisplay: "Graphics Designer" },
	{ value: "ui_ux_designer", valueToDisplay: "UI/UX Designer" },
	{ value: "frontend_developer", valueToDisplay: "Frontend Developer" },
	{ value: "backend_developer", valueToDisplay: "Backend Developer" },
	{ value: "full_stack_developer", valueToDisplay: "Full Stack Developer" },
	{ value: "mobile_app_developer", valueToDisplay: "Mobile App Developer" },
	{ value: "data_analyst", valueToDisplay: "Data Analyst" },
	{ value: "seo_specialist", valueToDisplay: "SEO Specialist" },
	{ value: "digital_marketer", valueToDisplay: "Digital Marketer" },
	{ value: "project_manager", valueToDisplay: "Project Manager" },
	{ value: "content_writer", valueToDisplay: "Content Writer" },
	{ value: "qa_engineer", valueToDisplay: "QA Engineer" },
];

export const companySizeOptions = [
	{ value: "1-10", valueToDisplay: "1-10" },
	{ value: "11-50", valueToDisplay: "11-50" },
	{ value: "51-200", valueToDisplay: "51-200" },
	{ value: "201-500", valueToDisplay: "201-500" },
	{ value: "501-1000", valueToDisplay: "501-1000" },
	{ value: "1001+", valueToDisplay: "1001+" },
];

export const industyTypeOptions = [
	{ value: "IT", valueToDisplay: "IT" },
	{ value: "Finance", valueToDisplay: "Finance" },
	{ value: "Healthcare", valueToDisplay: "Healthcare" },
	{ value: "Energy", valueToDisplay: "Energy" },
	{ value: "Manufacturing", valueToDisplay: "Manufacturing" },
	{ value: "Retail", valueToDisplay: "Retail" },
	{ value: "Education", valueToDisplay: "Education" },
	{ value: "Government", valueToDisplay: "Government" },
	{ value: "Other", valueToDisplay: "Other" },
];

// for multiple select inputs
export const skillOptions = [
	{ value: "javascript", label: "JavaScript" },
	{ value: "python", label: "Python" },
	{ value: "java", label: "Java" },
	{ value: "csharp", label: "C#" },
	{ value: "ruby", label: "Ruby" },
	{ value: "go", label: "Go" },
	{ value: "html", label: "HTML" },
	{ value: "css", label: "CSS" },
	{ value: "react", label: "React.js" },
	{ value: "angular", label: "Angular" },
	{ value: "vue", label: "Vue.js" },
	{ value: "nodejs", label: "Node.js" },
	{ value: "express", label: "Express.js" },
	{ value: "mongodb", label: "MongoDB" },
	{ value: "mysql", label: "MySQL" },
	{ value: "postgresql", label: "PostgreSQL" },
	{ value: "sql", label: "SQL" },
	{ value: "docker", label: "Docker" },
	{ value: "kubernetes", label: "Kubernetes" },
	{ value: "aws", label: "AWS" },
	{ value: "azure", label: "Azure" },
	{ value: "googlecloud", label: "Google Cloud" },
	{ value: "git", label: "Git" },
	{ value: "github", label: "GitHub" },
	{ value: "gitlab", label: "GitLab" },
	{ value: "ci_cd", label: "CI/CD" },
	{ value: "jest", label: "Jest" },
	{ value: "mocha", label: "Mocha" },
	{ value: "typescript", label: "TypeScript" },
	{ value: "sass", label: "Sass" },
	{ value: "graphql", label: "GraphQL" },
	{ value: "redux", label: "Redux" },
	{ value: "tailwindcss", label: "Tailwind CSS" },
	{ value: "bootstrap", label: "Bootstrap" },
	{ value: "webpack", label: "Webpack" },
	{ value: "firebase", label: "Firebase" },
	{ value: "jest", label: "Jest" },
	{ value: "selenium", label: "Selenium" },
	{ value: "scrum", label: "Scrum" },
	{ value: "agile", label: "Agile" },
	{ value: "vscode", label: "Visual Studio Code" },
	{ value: "docker", label: "Docker" },
	{ value: "linux", label: "Linux" },
	{ value: "windows", label: "Windows" },
	{ value: "machinelearning", label: "Machine Learning" },
	{ value: "deep_learning", label: "Deep Learning" },
	{ value: "tensorflow", label: "TensorFlow" },
	{ value: "pytorch", label: "PyTorch" },
	{ value: "opencv", label: "OpenCV" },
	{ value: "r", label: "R" },
	{ value: "tableau", label: "Tableau" },
	{ value: "powerbi", label: "Power BI" },
	{ value: "spark", label: "Apache Spark" },
	{ value: "hadoop", label: "Hadoop" },
	{ value: "sqlalchemy", label: "SQLAlchemy" },
	{ value: "elasticsearch", label: "Elasticsearch" },
	{ value: "redis", label: "Redis" },
	{ value: "kafka", label: "Apache Kafka" },
	{ value: "rabbitmq", label: "RabbitMQ" },
	{ value: "azuredevops", label: "Azure DevOps" },
	{ value: "jenkins", label: "Jenkins" },
	{ value: "cloudformation", label: "CloudFormation" },
	{ value: "ansible", label: "Ansible" },
	{ value: "terraform", label: "Terraform" },
	{ value: "nginx", label: "Nginx" },
	{ value: "apache", label: "Apache" },
	{ value: "rails", label: "Ruby on Rails" },
	{ value: "flutter", label: "Flutter" },
	{ value: "swift", label: "Swift" },
	{ value: "kotlin", label: "Kotlin" },
	{ value: "xcode", label: "Xcode" },
	{ value: "android", label: "Android Development" },
	{ value: "ios", label: "iOS Development" },
	{ value: "reactnative", label: "React Native" },
	{ value: "ember", label: "Ember.js" },
	{ value: "laravel", label: "Laravel" },
	{ value: "symfony", label: "Symfony" },
];

export const locationOptions = [
	{
		value: "kochi",
		label: "Kochi",
	},
	{ value: "kollam", label: "Kollam" },
	{ value: "kozhikode", label: "Kozhikode" },
	{ value: "alappuzha", label: "Alappuzha" },
	{ value: "ernakulam", label: "Ernakulam" },
	{ value: "idukki", label: "Idukki" },
	{ value: "kannur", label: "Kannur" },
	{ value: "kasaragod", label: "Kasaragod" },
	{ value: "kottayam", label: "Kottayam" },
	{ value: "malappuram", label: "Malappuram" },
	{ value: "palakkad", label: "Palakkad" },
	{ value: "pathanamthitta", label: "Pathanamthitta" },
	{ value: "thiruvananthapuram", label: "Thiruvananthapuram" },
	{ value: "thrissur", label: "Thrissur" },
	{ value: "wayanad", label: "Wayanad" },
];

export const professions = [
	{ value: "web_developer", label: "Web Developer" },
	{ value: "graphics_designer", label: "Graphics Designer" },
	{ value: "ui_ux_designer", label: "UI/UX Designer" },
	{ value: "frontend_developer", label: "Frontend Developer" },
	{ value: "backend_developer", label: "Backend Developer" },
	{ value: "full_stack_developer", label: "Full Stack Developer" },
	{ value: "mobile_app_developer", label: "Mobile App Developer" },
	{ value: "data_scientist", label: "Data Scientist" },
	{ value: "data_analyst", label: "Data Analyst" },
	{ value: "seo_specialist", label: "SEO Specialist" },
	{ value: "digital_marketer", label: "Digital Marketer" },
	{ value: "content_writer", label: "Content Writer" },
	{ value: "copywriter", label: "Copywriter" },
	{ value: "qa_engineer", label: "QA Engineer" },
	{ value: "project_manager", label: "Project Manager" },
	{ value: "product_manager", label: "Product Manager" },
	{ value: "business_analyst", label: "Business Analyst" },
	{ value: "network_administrator", label: "Network Administrator" },
	{ value: "system_administrator", label: "System Administrator" },
	{ value: "cybersecurity_specialist", label: "Cybersecurity Specialist" },
	{ value: "cloud_engineer", label: "Cloud Engineer" },
	{ value: "ai_ml_engineer", label: "AI/ML Engineer" },
	{ value: "teacher", label: "Teacher" },
	{ value: "professor", label: "Professor" },
	{ value: "accountant", label: "Accountant" },
	{ value: "financial_analyst", label: "Financial Analyst" },
	{ value: "banker", label: "Banker" },
	{ value: "lawyer", label: "Lawyer" },
	{ value: "doctor", label: "Doctor" },
	{ value: "nurse", label: "Nurse" },
	{ value: "pharmacist", label: "Pharmacist" },
	{ value: "civil_engineer", label: "Civil Engineer" },
	{ value: "mechanical_engineer", label: "Mechanical Engineer" },
	{ value: "electrical_engineer", label: "Electrical Engineer" },
	{ value: "chemical_engineer", label: "Chemical Engineer" },
	{ value: "architect", label: "Architect" },
	{ value: "chef", label: "Chef" },
	{ value: "pilot", label: "Pilot" },
	{ value: "writer", label: "Writer" },
	{ value: "artist", label: "Artist" },
	{ value: "photographer", label: "Photographer" },
	{ value: "video_editor", label: "Video Editor" },
	{ value: "musician", label: "Musician" },
	{ value: "actor", label: "Actor" },
	{ value: "entrepreneur", label: "Entrepreneur" },
	{ value: "student", label: "Student" },
];
// job portal data
export const categoryData = [
	{ value: "On-site", valueToDisplay: "On-site" },
	{ value: "Remote", valueToDisplay: "Remote" },
	{ value: "W-F-H", valueToDisplay: "W-F-H" },
	{ value: "Hybrid", valueToDisplay: "Hybrid" },
];

export const postedDateData = [
	"All",
	"Last Hour",
	"Last 24 Hours",
	"Last 7 Days",
	"Last 14 Days",
	"Last 30 Days",
];

export const experienceData = [
	{ value: "fresher", valueToDisplay: "Fresher" },
	{ value: "0-1", valueToDisplay: "0-1" },
	{ value: "1-2", valueToDisplay: "1-2" },
	{ value: "2-3", valueToDisplay: "2-3" },
	{ value: "4-6", valueToDisplay: "4-6" },
	{ value: ">6", valueToDisplay: ">6" },
];

export const filterSkillOptions = [
	{ value: "javascript", valueToDisplay: "JavaScript" },
	{ value: "python", valueToDisplay: "Python" },
	{ value: "java", valueToDisplay: "Java" },
	{ value: "csharp", valueToDisplay: "C#" },
	{ value: "ruby", valueToDisplay: "Ruby" },
	{ value: "go", valueToDisplay: "Go" },
	{ value: "html", valueToDisplay: "HTML" },
	{ value: "css", valueToDisplay: "CSS" },
	{ value: "react", valueToDisplay: "React.js" },
	{ value: "angular", valueToDisplay: "Angular" },
	{ value: "vue", valueToDisplay: "Vue.js" },
	{ value: "nodejs", valueToDisplay: "Node.js" },
	{ value: "express", valueToDisplay: "Express.js" },
	{ value: "mongodb", valueToDisplay: "MongoDB" },
	{ value: "mysql", valueToDisplay: "MySQL" },
	{ value: "postgresql", valueToDisplay: "PostgreSQL" },
	{ value: "sql", valueToDisplay: "SQL" },
	{ value: "docker", valueToDisplay: "Docker" },
	{ value: "kubernetes", valueToDisplay: "Kubernetes" },
	{ value: "aws", valueToDisplay: "AWS" },
	{ value: "azure", valueToDisplay: "Azure" },
	{ value: "googlecloud", valueToDisplay: "Google Cloud" },
	{ value: "git", valueToDisplay: "Git" },
	{ value: "github", valueToDisplay: "GitHub" },
	{ value: "gitlab", valueToDisplay: "GitLab" },
	{ value: "ci_cd", valueToDisplay: "CI/CD" },
	{ value: "jest", valueToDisplay: "Jest" },
	{ value: "mocha", valueToDisplay: "Mocha" },
	{ value: "typescript", valueToDisplay: "TypeScript" },
	{ value: "sass", valueToDisplay: "Sass" },
	{ value: "graphql", valueToDisplay: "GraphQL" },
	{ value: "redux", valueToDisplay: "Redux" },
	{ value: "tailwindcss", valueToDisplay: "Tailwind CSS" },
	{ value: "bootstrap", valueToDisplay: "Bootstrap" },
	{ value: "webpack", valueToDisplay: "Webpack" },
	{ value: "firebase", valueToDisplay: "Firebase" },
	{ value: "jest", valueToDisplay: "Jest" },
	{ value: "selenium", valueToDisplay: "Selenium" },
	{ value: "scrum", valueToDisplay: "Scrum" },
	{ value: "agile", valueToDisplay: "Agile" },
	{ value: "vscode", valueToDisplay: "Visual Studio Code" },
	{ value: "docker", valueToDisplay: "Docker" },
	{ value: "linux", valueToDisplay: "Linux" },
	{ value: "windows", valueToDisplay: "Windows" },
	{ value: "machinelearning", valueToDisplay: "Machine Learning" },
	{ value: "deep_learning", valueToDisplay: "Deep Learning" },
	{ value: "tensorflow", valueToDisplay: "TensorFlow" },
	{ value: "pytorch", valueToDisplay: "PyTorch" },
	{ value: "opencv", valueToDisplay: "OpenCV" },
	{ value: "r", valueToDisplay: "R" },
	{ value: "tableau", valueToDisplay: "Tableau" },
	{ value: "powerbi", valueToDisplay: "Power BI" },
	{ value: "spark", valueToDisplay: "Apache Spark" },
	{ value: "hadoop", valueToDisplay: "Hadoop" },
	{ value: "sqlalchemy", valueToDisplay: "SQLAlchemy" },
	{ value: "elasticsearch", valueToDisplay: "Elasticsearch" },
	{ value: "redis", valueToDisplay: "Redis" },
	{ value: "kafka", valueToDisplay: "Apache Kafka" },
	{ value: "rabbitmq", valueToDisplay: "RabbitMQ" },
	{ value: "azuredevops", valueToDisplay: "Azure DevOps" },
	{ value: "jenkins", valueToDisplay: "Jenkins" },
	{ value: "cloudformation", valueToDisplay: "CloudFormation" },
	{ value: "ansible", valueToDisplay: "Ansible" },
	{ value: "terraform", valueToDisplay: "Terraform" },
	{ value: "nginx", valueToDisplay: "Nginx" },
	{ value: "apache", valueToDisplay: "Apache" },
	{ value: "rails", valueToDisplay: "Ruby on Rails" },
	{ value: "flutter", valueToDisplay: "Flutter" },
	{ value: "swift", valueToDisplay: "Swift" },
	{ value: "kotlin", valueToDisplay: "Kotlin" },
	{ value: "xcode", valueToDisplay: "Xcode" },
	{ value: "android", valueToDisplay: "Android Development" },
	{ value: "ios", valueToDisplay: "iOS Development" },
	{ value: "reactnative", valueToDisplay: "React Native" },
	{ value: "ember", valueToDisplay: "Ember.js" },
	{ value: "laravel", valueToDisplay: "Laravel" },
	{ value: "symfony", valueToDisplay: "Symfony" },
];

export const manageJobsMonthOptions = [
	{ value: "Last 6 Months", valueToDisplay: "Last 6 Months" },
	{ value: "Last 12 Months", valueToDisplay: "Last 12 Months" },
	{ value: "Last 16 Months", valueToDisplay: "Last 16 Months" },
	{ value: "Last 24 Months", valueToDisplay: "Last 24 Months" },
	{ value: "Last 5 Year", valueToDisplay: "Last 5 Year" },
];

export const salaryRanges = [
	{ value: "0-20000", valueToDisplay: "0-20,000" },
	{ value: "20001-40000", valueToDisplay: "20,001-40,000" },
	{ value: "40001-60000", valueToDisplay: "40,001-60,000" },
	{ value: "60001-80000", valueToDisplay: "60,001-80,000" },
	{ value: "80001-100000", valueToDisplay: "80,001-100,000" },
	{ value: "100001-120000", valueToDisplay: "100,001-120,000" },
	{ value: "120001-140000", valueToDisplay: "120,001-140,000" },
	{ value: "140001-160000", valueToDisplay: "140,001-160,000" },
	{ value: "160001-180000", valueToDisplay: "160,001-180,000" },
	{ value: "180001-200000", valueToDisplay: "180,001-200,000" },
	{ value: "200001+", valueToDisplay: "200,001+" },
];

export const joiningDayRange = [
	{ value: "immediate", valueToDisplay: "Immediate" },
	{ value: "within_1_week", valueToDisplay: "Within 1 Week" },
	{ value: "within_2_weeks", valueToDisplay: "Within 2 Weeks" },
	{ value: "within_1_month", valueToDisplay: "Within 1 Month" },
	{ value: "within_2_months", valueToDisplay: "Within 2 Months" },
	{ value: "within_3_months", valueToDisplay: "Within 3 Months" },
];


