name: Deploy Backend and Frontend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js (for building the frontend)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    # Step 3: Install dependencies and build frontend
    - name: Install Dependencies and Build Frontend
      working-directory: client
      env:
        VITE_API_URL: ${{ secrets.VITE_API_URL }}
        VITE_CLIENT_URL: ${{ secrets.VITE_CLIENT_URL }}
        VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
        VITE_NODE_ENV: ${{ secrets.VITE_NODE_ENV }}
        VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY }}
      run: |
        npm install || { echo "Dependency installation failed"; exit 1; }
        npm run build || { echo "Client build failed"; exit 1; }

    # Step 4: SSH into EC2 and Deploy Backend
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          # Navigate to the backend project directory
          cd ~/jobportal
          echo "Pulling latest changes from main branch"
          git pull origin main

          # Navigate to the server folder and install dependencies
          cd server
          echo "Installing backend dependencies"
          npm install || { echo "Dependency installation failed"; exit 1; }

          # Restart PM2 process
          echo "Restarting PM2 process"
          pm2 restart all

    # Step 5: Upload Frontend to EC2
    - name: Upload Frontend to EC2
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        source: client/dist/
        target: ~/jobportal/frontend-temp/

    # Step 6: SSH into EC2 to deploy frontend
    - name: Deploy Frontend
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_KEY }}
        port: 22
        script: |
          # Backup current frontend
          echo "Backing up current frontend"
          if [ -d "~/frontend" ]; then
            sudo mv ~/frontend ~/frontend-backup-$(date +%Y%m%d_%H%M%S)
          fi

          # Remove the existing frontend-temp directory if it exists
          if [ -d "~/frontend/frontend-temp" ]; then
            echo "Removing existing temp files"
            sudo rm -rf ~/frontend/frontend-temp
          fi

          # Move the new frontend to the deployment folder
          echo "Deploying new frontend"
          sudo mv ~/jobportal/frontend-temp ~/frontend

          # Set permissions for frontend
          echo "Setting permissions for frontend"
          sudo chown -R www-data:www-data ~/frontend
          sudo chmod -R 755 ~/frontend

          # Restart NGINX
          echo "Restarting NGINX"
          sudo systemctl restart nginx

          # Deployment completed
          echo "Deployment completed"
